# Generated by Django 5.1.4 on 2025-03-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='PC name or hostname', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IPv4 or IPv6 address', unpack_ipv4=True)),
                ('mac_address', models.CharField(help_text='MAC address of the PC', max_length=100, unique=True)),
                ('os', models.CharField(help_text='Operating system running on the PC', max_length=100)),
                ('cpu', models.CharField(help_text='CPU model and details', max_length=100)),
            ],
        ),
    ]
