# Generated by Django 5.1.4 on 2025-03-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedpc',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='connectedpc',
            name='os',
        ),
    ]
