# Generated by Django 5.1.4 on 2025-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_connectedpc_cpu_remove_connectedpc_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ConnectedPC',
        ),
    ]
